version: '3.3'
services:
  backend:
    build:
      context: ./backend
    command: gunicorn mushroomApp.wsgi --bind 0.0.0.0:8000
    image: 698408480519.dkr.ecr.eu-north-1.amazonaws.com/rep:web
    ports:
      - "8000:8000"
  frontend:
    image: 698408480519.dkr.ecr.eu-north-1.amazonaws.com/rep:frontend
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://13.50.15.63:8000
        REACT_APP_FRONTEND_BASE_URL: http://13.50.15.63:3000
    ports:
      - "3000:3000"
    volumes:
      - frontend:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  frontend:
