# Generated by Django 4.1.8 on 2023-04-21 12:16

import bson.objectid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0002_remove_mushroom_area_remove_mushroom_edible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='id',
            field=models.AutoField(default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
    ]
