# Generated by Django 4.1.7 on 2023-03-31 15:44

import bson.objectid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0009_rename_latin_name_mushroom_s_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='id',
            field=models.AutoField(default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='list_mislabel',
            field=models.TextField(default='No data'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='name',
            field=models.CharField(default='No data', max_length=255),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='s_name',
            field=models.CharField(default='No data', max_length=255),
        ),
    ]
