# Generated by Django 4.1.8 on 2023-04-19 11:46

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mushroomIdentifyer', '0010_alter_mushroom_id_alter_mushroom_list_mislabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='image_urls',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='list_mislabel',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
