name: Postman Auto-Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/backend/requirements.txt

    - name: Install Newman
      run: npm install -g newman

    - name: Run migrations
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.8.16/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.16/x64/lib
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
        MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        echo $MONGO_HOST && echo $MONGO_DB_NAME && echo $MONGO_USERNAME && echo $MONGO_PASSWORD && echo $SECRET_KEY
        python3 app/backend/manage.py migrate

    - name: Run server and Postman tests
      run: |
        python3 app/backend/manage.py runserver &
        newman run app/backend/tests/DAT251.postman_collection.json
