name: Postman Auto-Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/backend/requirements.txt

    - name: Install Newman
      run: npm install -g newman

    - name: Run backend
      run: |
        export MONGO_HOST=$MONGO_HOST
        export MONGO_DB_NAME=$MONGO_DB_NAME
        export MONGO_USERNAME=$MONGO_USERNAME
        export MONGO_PASSWORD=$MONGO_PASSWORD
        export SECRET_KEY=$SECRET_KEY
        python3 app/backend/manage.py runserver

    - name: Run Postman tests
      run: newman run app/backend/tests/DAT251.postman_collection.json

